import type { Bilingual } from '../types';

const en = {
    tag: 'LIMITS AND OPEN QUESTIONS',
    title: 'What is not proven',
    subtitle:
      'Every number on this page comes from a specific setup, and most of them come from one model on one domain. This section exists so the claims above can be read at their real strength.',
    groups: [
      {
        name: 'Ordo-M',
        items: [
          'The memory arm on a real domain has not been measured. The bar is set at 67.8% and the arm behind it is empty.',
          'The one real domain tested is 96% code symbols, where the entity name is already a usable key. The product scenario — a company wiki — is prose, and the self-naming metric already shows where it breaks: 100% of code records name themselves, only 53.8% of prose sections do.',
          'Addressing from hidden state was tested as a general solution and closed: at the position where the memory is read, the identity of the entity is no longer present in the residual stream.',
          'An oracle measurement shows the ceiling is real — supplying the address externally is worth +37.0 points on questions that do not name the entity — so the whole limitation sits in computing the address, not in the memory.',
          'Everything is measured on one 8B model. Nothing has been run on larger models or on other families, including mixture-of-experts.',
          'The evaluation questions were generated by a model. Their defect rate is known as a range — 0.8% to 25.6% — not as a number. It affects absolute percentages directly and comparisons between arms only weakly.',
        ],
      },
      {
        name: 'OrdoGen',
        items: [
          'Everything is measured on one 0.6B model at a pinned revision. Whether the same heads carry the same role in a larger model is unknown.',
          'No transfer to 64K or 128K has been shown for the learned selector, and prompt-level interventions provably do not extrapolate that far.',
          'Compositional tasks — multi-hop, aggregation, update ordering — do not benefit from any intervention tried so far. On a 0.6B model the capability may simply be absent.',
          'There is no subquadratic speed-up yet. The current prototype runs a second dense prefill and is slower end to end than the baseline.',
          'Zero-ablation is not equivalent to removing heads during training, and attention mass is not a complete account of the computation.',
          'The primary results have not been replicated independently.',
        ],
      },
    ],
    nextTitle: 'What comes next',
    nextItems: [
      'Ordo-M: measure the memory arm on the same 825 records and the same 183 questions — the one thing the acceptance criterion is missing.',
      'Ordo-M: confirm the longest-mention selection rule on GPU and make it the default.',
      'Ordo-M: take a second domain made of prose and repeat the comparison from scratch. That is the one that answers the product question.',
      'OrdoGen: replace recall with an outcome-aware objective, so the selector is scored on repairs kept rather than blocks found.',
      'OrdoGen: hard selected-block attention with a fused kernel, and only then a move to 64K and 128K.',
    ],
  };

/** RU is typed against EN, so a missing or renamed key fails the build. */
export const limits: Bilingual<typeof en> = {
  en,
  ru: {
    tag: 'ГРАНИЦЫ И ОТКРЫТЫЕ ВОПРОСЫ',
    title: 'Что не доказано',
    subtitle:
      'Каждое число на этой странице получено в конкретной постановке, и большинство — на одной модели и одном домене. Этот раздел существует, чтобы утверждения выше читались с их настоящей силой.',
    groups: [
      {
        name: 'Ordo-M',
        items: [
          'Плечо памяти на настоящем домене не замерено. Планка выставлена на 67.8%, и за ней пока пусто.',
          'Единственный проверенный настоящий домен на 96% состоит из символов кода, где имя сущности — готовый ключ. Продуктовый сценарий — вики компании — это проза, и метрика самоназывания уже показывает, где он сломается: 100% записей кода называют себя, у прозы — только 53.8%.',
          'Адресация по скрытому состоянию проверена как общее решение и закрыта: в позиции, где память читается, личности сущности в остаточном потоке уже нет.',
          'Оракульный замер показывает, что потолок реален: подача адреса снаружи стоит +37.0 пункта на вопросах, не называющих сущность. Значит вся проблема сидит в вычислении адреса, а не в памяти.',
          'Всё измерено на одной модели 8B. Ни на моделях крупнее, ни на других семействах, включая MoE, прогонов не было.',
          'Вопросы для замера сгенерированы моделью. Доля брака в них известна вилкой — 0.8%–25.6%, — а не числом. На абсолютные проценты это влияет прямо, на сравнение плеч — слабо.',
        ],
      },
      {
        name: 'OrdoGen',
        items: [
          'Всё измерено на одной модели 0.6B на зафиксированной ревизии. Несут ли те же головы ту же роль в модели крупнее — неизвестно.',
          'Перенос обучаемого селектора на 64K и 128K не показан, а промптовые вмешательства доказанно так далеко не экстраполируются.',
          'Композиционные задачи — многошаговые вопросы, агрегация, порядок обновлений — не выигрывают ни от одного испробованного вмешательства. На модели 0.6B этой способности может просто не быть.',
          'Субквадратичного ускорения пока нет. Нынешний прототип делает второй плотный прогон и сквозным замером медленнее базового.',
          'Зануление голов не эквивалентно их удалению при обучении, а масса внимания — не полное объяснение вычисления.',
          'Основные результаты не воспроизведены независимо.',
        ],
      },
    ],
    nextTitle: 'Что дальше',
    nextItems: [
      'Ordo-M: замерить плечо памяти на тех же 825 записях и тех же 183 вопросах — единственное, чего не хватает критерию приёмки.',
      'Ordo-M: подтвердить правило «самое длинное упоминание» на карте и сделать его умолчанием.',
      'Ordo-M: взять второй домен, прозаический, и повторить сравнение целиком. Именно он отвечает на продуктовый вопрос.',
      'OrdoGen: заменить полноту выбора блоков целью, зависящей от исхода, чтобы селектор оценивался по удержанным починкам, а не по найденным блокам.',
      'OrdoGen: жёсткое внимание по выбранным блокам со слитым ядром, и только после этого переход на 64K и 128K.',
    ],
  },
};
