import type { Bilingual } from '../types';

const en = {
    tag: 'LIMITS AND OPEN QUESTIONS',
    title: 'What is not proven',
    subtitle:
      'Every number on this page comes from a specific setup, and most of them come from one model on one domain. This section exists so the claims above can be read at their real strength.',
    groups: [
      {
        name: 'Ordo-M',
        items: [
          'The M1 bar was cleared by 0.3 points at a seed spread of 1.38. That is reached, not significantly exceeded, and it should be read that way until more seeds exist.',
          'It was cleared on a corpus prepared by an external model. The product promise is that a client loads a raw wiki, and raw text demonstrably carries nothing — so the gap between the demo and the promise is one specific missing piece: getting a local model to choose what to write about.',
          'A corpus written by the frozen base itself is statistically indistinguishable from raw text. Its facts are fine; its coverage of what gets asked is half.',
          'The prose bar is set at 79.9% and the memory arm behind it has not been run. Prose is also a different question — the base already knows that domain, so it measures addition rather than acquisition.',
          'On prose the indirect bucket is 20.6% of the set. Retrieval answers it; the memory is silent on it by construction, because no mention means no address.',
          'Text damage is a real cost and only half the criterion is met. The working point holds knowledge at +22.5% perplexity on entity mentions, against +0.00% on prose that names nothing.',
          'The width of the memory slot has never been varied on a real domain. It is the one capacity axis an earlier synthetic bench called the only true limit, and every domain run so far has used the inherited default.',
          'Everything is measured on one 8B model. Nothing has been run on larger models or on other families, including mixture-of-experts.',
          'The evaluation questions were generated by a model. Their defect rate is known as a range — 0.8% to 25.6% — not as a number.',
        ],
      },
      {
        name: 'OrdoGen',
        items: [
          'Everything is measured on one 0.6B model at a pinned revision. Whether the same heads carry the same role in a larger model is unknown.',
          'No transfer to 64K or 128K has been shown for the learned selector, and prompt-level interventions provably do not extrapolate that far.',
          'Compositional tasks — multi-hop, aggregation, update ordering — do not benefit from any intervention tried so far. On a 0.6B model the capability may simply be absent.',
          'There is no subquadratic speed-up yet. The current prototype runs a second dense prefill and is slower end to end than the baseline.',
          'Zero-ablation is not equivalent to removing heads during training, and attention mass is not a complete account of the computation.',
          'The primary results have not been replicated independently.',
        ],
      },
    ],
    nextTitle: 'What comes next',
    nextItems: [
      'Ordo-M: turn the width of the memory slot on a real domain — the last untested capacity axis, and the one standing between 38.3% coverage and 49.7%.',
      'Ordo-M: teach a local generator to choose what to write about. Coverage is measurable on a laptop now, so the loop is cheap.',
      'Ordo-M: run the memory arm on the prose domain against the 79.9% bar.',
      'OrdoGen: replace recall with an outcome-aware objective, so the selector is scored on repairs kept rather than blocks found.',
      'OrdoGen: hard selected-block attention with a fused kernel, and only then a move to 64K and 128K.',
    ],
  };

/** RU is typed against EN, so a missing or renamed key fails the build. */
export const limits: Bilingual<typeof en> = {
  en,
  ru: {
    tag: 'ГРАНИЦЫ И ОТКРЫТЫЕ ВОПРОСЫ',
    title: 'Что не доказано',
    subtitle:
      'Каждое число на этой странице получено в конкретной постановке, и большинство — на одной модели и одном домене. Этот раздел существует, чтобы утверждения выше читались с их настоящей силой.',
    groups: [
      {
        name: 'Ordo-M',
        items: [
          'Планка M1 взята с запасом 0.3 пункта при разбросе по зёрнам 1.38. Это «достигнуто», а не «значимо превышено», и читать это следует именно так, пока зёрен не станет больше.',
          'Взята она на корпусе, подготовленном внешней моделью. Продуктовое обещание — что клиент грузит сырую вики, а сырой текст доказанно не несёт ничего; значит разрыв между демонстрацией и обещанием сводится к одному конкретному недостающему куску: научить локальную модель выбирать, о чём писать.',
          'Корпус, написанный самой замороженной базой, статистически неотличим от сырого текста. Факты в нём в порядке; покрытие того, о чём спрашивают, вдвое ниже.',
          'Планка для прозы выставлена на 79.9%, и плечо памяти за ней не прогонялось. Проза — к тому же другой вопрос: базовая модель этот домен уже знает, поэтому там меряется добавление, а не приобретение.',
          'На прозе косвенная корзина составляет 20.6% набора. Поиск на неё отвечает; память по построению молчит, потому что нет упоминания — нет адреса.',
          'Порча текста — настоящая цена, и выполнена лишь половина критерия. Рабочая точка держит знание при +22.5% перплексии на упоминаниях сущностей против +0.00% на прозе, которая никого не называет.',
          'Ширину слота памяти на настоящем домене не меняли ни разу. Это единственная ось ёмкости, которую более ранний синтетический стенд назвал настоящим пределом, а все доменные прогоны шли на унаследованном умолчании.',
          'Всё измерено на одной модели 8B. Ни на моделях крупнее, ни на других семействах, включая MoE, прогонов не было.',
          'Вопросы для замера сгенерированы моделью. Доля брака в них известна вилкой — 0.8%–25.6%, — а не числом.',
        ],
      },
      {
        name: 'OrdoGen',
        items: [
          'Всё измерено на одной модели 0.6B на зафиксированной ревизии. Несут ли те же головы ту же роль в модели крупнее — неизвестно.',
          'Перенос обучаемого селектора на 64K и 128K не показан, а промптовые вмешательства доказанно так далеко не экстраполируются.',
          'Композиционные задачи — многошаговые вопросы, агрегация, порядок обновлений — не выигрывают ни от одного испробованного вмешательства. На модели 0.6B этой способности может просто не быть.',
          'Субквадратичного ускорения пока нет. Нынешний прототип делает второй плотный прогон и сквозным замером медленнее базового.',
          'Зануление голов не эквивалентно их удалению при обучении, а масса внимания — не полное объяснение вычисления.',
          'Основные результаты не воспроизведены независимо.',
        ],
      },
    ],
    nextTitle: 'Что дальше',
    nextItems: [
      'Ordo-M: повернуть ширину слота памяти на настоящем домене — последнюю непроверенную ось ёмкости, ту самую, что стоит между покрытием 38.3% и 49.7%.',
      'Ordo-M: научить локальный генератор выбирать, о чём писать. Покрытие теперь считается на ноутбуке, поэтому цикл дешёвый.',
      'Ordo-M: прогнать плечо памяти на прозаическом домене против планки 79.9%.',
      'OrdoGen: заменить полноту выбора блоков целью, зависящей от исхода, чтобы селектор оценивался по удержанным починкам, а не по найденным блокам.',
      'OrdoGen: жёсткое внимание по выбранным блокам со слитым ядром, и только после этого переход на 64K и 128K.',
    ],
  },
};
